### ISSUE TITLE
.gitignore file in the template itself is not correct

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml-model-template#16]
This gitignore should skip docs, target AND the model_name files, as they are all generated in the github actions

**Comment by sierra-moxon** [comment]
This repo is archived.  Equivalent functionality is now hosted at http://linkml/linkml-project-cookiecutter/.  If we close an issue you still are waiting on, please feel free to reach out on the issue tracker and we will add it to the cookie-cutter.  https://github.com/linkml/linkml/issues.
