### ISSUE TITLE
PyPI is not accepting token according to PYPI_SETUP.md

### ISSUE THREAD

**Issue by turbomam** [linkml/linkml-model-template#17]
I think I have followed `PYPI_SETUP.md` verbatim.

I **was** able to publish my package from [turbomam/ccdhmodel-from-template](https://github.com/turbomam/ccdhmodel-from-template) following the manual, password-based instructions in `PYPI_SETUP.md`.

```
Warning:  It looks like you are trying to use an API token to authenticate in the package index and your token value does not start with "pypi-" as it typically should. This may cause an authentication error. Please verify that you have copied your token properly if such an error occurs.
Checking dist/ccdhmodel_from_template-0.0.2-py3-none-any.whl: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
Checking dist/ccdhmodel_from_template-0.0.2.tar.gz: PASSED, with warnings
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
Uploading distributions to https://upload.pypi.org/legacy/
Uploading ccdhmodel_from_template-0.0.2-py3-none-any.whl

  0%|          | 0.00/268k [00:00<?, ?B/s]
  3%|▎         | 8.00k/268k [00:00<00:04, 54.5kB/s]
 98%|█████████▊| 264k/268k [00:00<00:00, 1.19MB/s] 
100%|██████████| 268k/268k [00:00<00:00, 638kB/s] 
NOTE: Try --verbose to see response content.
HTTPError: 403 Forbidden from https://upload.pypi.org/legacy/
Invalid or non-existent authentication information. See https://pypi.org/help/#invalid-auth for more information.
```

**Comment by turbomam** [comment]
@wdduncan and I spent about two hours on this today. @cmungall provide some feedback too. We could not get the `pypi-publish.yaml` GH action to work, although a similar action in nmdc-schema does work.

I can publish my package to PyPI manually, following the initial steps in `PYPI_SETUP.md`. I'll put that in my repo's Makefile.

I switched to authenticating with a PyPI token saved in `~/.pypirc` instead of a chaced PyPI username and password.

```
[pypi]
username = __token__
password = pypi-...
```

**Comment by turbomam** [comment]
Maybe I (and the template) have too few curly brackets wrapping the secret name in the GH action?

**Comment by sierra-moxon** [comment]
This repo is archived.  Equivalent functionality is now hosted at http://linkml/linkml-project-cookiecutter/.  If we close an issue you still are waiting on, please feel free to reach out on the issue tracker and we will add it to the cookie-cutter.  https://github.com/linkml/linkml/issues.
