### ISSUE TITLE
Consider moving configure.py to a separate repository

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml-model-template#3]
We may not want to copy the configure.py code as a part of the template.  It might make more sense to have a separate configure package that one installs and runs on a template

**Comment by sierra-moxon** [comment]
This repo is archived.  Equivalent functionality is now hosted at http://linkml/linkml-project-cookiecutter/.  If we close an issue you still are waiting on, please feel free to reach out on the issue tracker and we will add it to the cookie-cutter.  https://github.com/linkml/linkml/issues.
