### ISSUE TITLE
Consider script gif as part of doc

### ISSUE THREAD

**Issue by hsolbrig** [linkml/linkml-model-template#4]
We should consider something akin to the animated command line found  in the README for https://github.com/pypa/pipenv

**Comment by sierra-moxon** [comment]
This repo is archived.  Equivalent functionality is now hosted at http://linkml/linkml-project-cookiecutter/.  If we close an issue you still are waiting on, please feel free to reach out on the issue tracker and we will add it to the cookie-cutter.  https://github.com/linkml/linkml/issues.
