### ISSUE TITLE
Where is config.sh?

### ISSUE THREAD

**Issue by smrgeoinfo** [linkml/linkml-model-template#5]
I'm trying to set this up on Windows 10; got the template cloned and set up, update config.yaml.  Instructions say to run 'config.sh', which seems like it should be some kind of shell script, but there is not config.sh in the repo. Is this specific to Linux?

**Comment by hsolbrig** [comment]
Hang on -- this is not ready for prime time ... use linkml-template for the time being

**Comment by smrgeoinfo** [comment]
Sorry about that.  I'd be happy to help with testing debugging when this is ready.

**Comment by hsolbrig** [comment]
No problem.  We're still coming to terms with actually being visible... reminds me of the old Haskell motto, something along the lines of "Avoid success at all costs".

Thanks!
