### ISSUE TITLE
How to include examples and tests in a templated repo

### ISSUE THREAD

**Issue by cmungall** [linkml/linkml-model-template#6]
I think it's good practice to always include example instance data with any schema. What is our best practice here?

linkml allows inclusion of examples in the schema, but I like also having a folder examples/ populated by one of

 * rdf instances
 * yaml
 * json
 * csvs

For example, I just started populating some examples for KGCL:

https://github.com/cmungall/knowledge-graph-change-language/blob/master/examples/de-novo.yaml

I think it would be useful if the template included a github action that would use the loaders/dumpers to represent the instance data in alternate serializations.

This also serves as a useful unit test: if the example fails to convert due to a missing slot declaration we know we have done something wrong in the schema

Alternatively, this could be done by seeding the repo with some python tests. This is a bit more 'pythonic', and not everyone who uses linkml wants or needs to know about python-level stuff -- but it can be useful.

For example, in the same repo I have a basic test that parsers examples in the examples/ folder and uses the dumpers:

https://github.com/cmungall/knowledge-graph-change-language/blob/master/tests/test_conversion.py

Is this good practice? Should I instead use `tests/inputs/`?

Would it make sense for the template to include some stub tests that parse all files in the example repo and tries roundtripping through all formats?

As an aside, I am having issues using generic loaders, perhaps due to the lack of a discriminator field in the metamodel, so I end up writing more bespoke code like this:

https://github.com/cmungall/knowledge-graph-change-language/blob/master/kgcl/utils.py#L28-L43

should I be doing this a smarter way?

**Comment by cmungall** [comment]
Also it would be awesome to include the examples in the markdowngen

e.g. if test data uses a class C, then include it in C.md

**Comment by sierra-moxon** [comment]
linkml-run-examples now handles many of these features.
